### ISSUE TITLE
If speedtest crashes, the whole process locks up

### ISSUE THREAD

**Issue by gergnz** [gergnz/aussiebbmgt#2]
```
Booting speedtest
(node:12968) UnhandledPromiseRejectionWarning: Error: No node found for selector: #main-content > div.button__wrapper > div > button
    at assert (/app/node_modules/puppeteer-core/lib/helper.js:279:11)
    at DOMWorld.click (/app/node_modules/puppeteer-core/lib/DOMWorld.js:366:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getSpeed (/app/index.js:54:5)
    at async runSpeedTest (/app/index.js:97:16)
  -- ASYNC --
    at Frame.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
    at getSpeed (/app/index.js:54:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runSpeedTest (/app/index.js:97:16)
(node:12968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gergnz** [comment]
https://github.com/gergnz/aussiebbmgt/blob/master/runforever.py#L76
